"""Example price table reconstructed from the owner's proposal for a 5 576 m² medical centre (9 000 000 ₽).

Marked is_example=True: the panel shows a warning until the owner replaces it with real rates.
"""

from decimal import Decimal as D

EXAMPLE_PRICE_TABLE = {
    "is_example": True,
    "sections": [
        {
            "code": "OBS",
            "name": "Обследование конструкций и инженерных систем, обмеры",
            "description": "Визуальное и инструментальное обследование, обмерные работы, фотофиксация дефектов.",
            "stage": "pre",
            "rate_per_m2": D("54"),
            "min_price": D("80000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "TZ",
            "name": "Техническое заключение по результатам обследования",
            "description": "Альбом технического заключения с учётом ГОСТ 31937-2024.",
            "stage": "pre",
            "rate_per_m2": D("36"),
            "min_price": D("60000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "AR",
            "name": "Архитектурные решения (АР)",
            "description": "Планы, кладочные планы, заполнение проёмов, экспликации, отделка помещений.",
            "stage": "rd",
            "rate_per_m2": D("170"),
            "min_price": D("150000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "TX",
            "name": "Технологические решения (ТХ)",
            "description": "Медицинская технология: расстановка кабинетов и постов, спецификации оборудования.",
            "stage": "rd",
            "rate_per_m2": D("188"),
            "min_price": D("150000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "EOM",
            "name": "Электроснабжение и электроосвещение (ЭОМ)",
            "description": "Внутренние сети электроснабжения и освещения, заземление, питание медоборудования.",
            "stage": "rd",
            "rate_per_m2": D("215"),
            "min_price": D("150000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "VK",
            "name": "Водоснабжение и водоотведение (ВК)",
            "description": "Внутренние системы водоснабжения и водоотведения, узлы учёта.",
            "stage": "rd",
            "rate_per_m2": D("143"),
            "min_price": D("100000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "OVIK",
            "name": "Отопление, вентиляция и кондиционирование (ОВиК)",
            "description": "Отопление, приточно-вытяжная вентиляция, кондиционирование и холодоснабжение.",
            "stage": "rd",
            "rate_per_m2": D("278"),
            "min_price": D("150000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "SS",
            "name": "Слаботочные системы (СС)",
            "description": "СКС, ЛВС, СКУД, видеонаблюдение, АПС, СОУЭ, вызов персонала.",
            "stage": "rd",
            "rate_per_m2": D("170"),
            "min_price": D("100000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "PB",
            "name": "Мероприятия по обеспечению пожарной безопасности (ПБ)",
            "description": "Пожарные отсеки, СОУЭ, АПС, дымоудаление, противопожарные преграды.",
            "stage": "rd",
            "rate_per_m2": D("179"),
            "min_price": D("100000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "POS",
            "name": "Организация строительства (ПОС/ПОР)",
            "description": "Проект организации работ, стройгенплан, подготовительные работы.",
            "stage": "rd",
            "rate_per_m2": D("45"),
            "min_price": D("60000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "OOS",
            "name": "Охрана окружающей среды (ООС)",
            "description": "Мероприятия по защите от шума и вибрации инженерного оборудования.",
            "stage": "rd",
            "rate_per_m2": D("36"),
            "min_price": D("50000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "ODI",
            "name": "Обеспечение доступа инвалидов (ОДИ)",
            "description": "Решения для маломобильных групп населения.",
            "stage": "rd",
            "rate_per_m2": D("36"),
            "min_price": D("50000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "PP",
            "name": "Проект перепланировки и переустройства",
            "description": "Проект перепланировки, техническое заключение для Росреестра.",
            "stage": "extra",
            "rate_per_m2": D("63"),
            "min_price": D("80000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "SM",
            "name": "Сметная документация (СМ)",
            "description": "Локальные и сводные сметные расчёты.",
            "stage": "extra",
            "rate_per_m2": D("80"),
            "min_price": D("100000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
    ],
    "object_types": {
        "Медицинский центр / клиника": D("1.0"),
        "Поликлиника": D("1.0"),
        "Стоматология": D("0.95"),
        "Лаборатория": D("1.1"),
        "Диагностический центр": D("1.1"),
        "Больница / стационар": D("1.2"),
    },
    "modifiers": [
        {"code": "reconstruction", "name": "Реконструкция / капремонт", "multiplier": D("1.10")},
        {"code": "clean_rooms", "name": "Чистые помещения / операционные", "multiplier": D("1.25")},
        {"code": "complex_medtech", "name": "Сложная медтехнология (КТ, МРТ, рентген)", "multiplier": D("1.15")},
        {"code": "urgent", "name": "Срочность (сокращённые сроки)", "multiplier": D("1.20")},
    ],
    "regions": {},
    "area_steps": [
        {"from_m2": D("0"), "multiplier": D("1.30")},
        {"from_m2": D("300"), "multiplier": D("1.0")},
        {"from_m2": D("3000"), "multiplier": D("1.0")},
    ],
}
