"""Example price table (is_example=True: the panel warns until the owner confirms the numbers).

Standard package = 5 sections АР, ЭОМ, ВК, ОВиК, СС (weights sum to 1). Package price by area from the owner:
100 m² -> 0.8-1.0 mln, 800 m² -> 2 mln, 1500 m² -> 3.5 mln. Points 3000 and 5000 m² are extrapolated and must be
confirmed. Section weights and extra sections are proportions from the owner's 9 mln proposal (Medscan).
"""

from decimal import Decimal as D

EXAMPLE_PRICE_TABLE = {
    "is_example": True,
    "package_curve": [
        {"area_m2": D("100"), "price": D("900000")},
        {"area_m2": D("800"), "price": D("2000000")},
        {"area_m2": D("1500"), "price": D("3500000")},
        {"area_m2": D("3000"), "price": D("6000000")},
        {"area_m2": D("5000"), "price": D("8500000")},
    ],
    "sections": [
        # Standard package (default selected), weights sum to 1.0
        {
            "code": "AR",
            "name": "Архитектурные решения (АР)",
            "description": "Планы, кладочные планы, заполнение проёмов, экспликации, отделка помещений.",
            "stage": "rd",
            "weight": D("0.175"),
            "min_price": D("100000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "EOM",
            "name": "Электроснабжение и электроосвещение (ЭОМ)",
            "description": "Внутренние сети электроснабжения и освещения, заземление, питание медоборудования.",
            "stage": "rd",
            "weight": D("0.220"),
            "min_price": D("100000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "VK",
            "name": "Водоснабжение и водоотведение (ВК)",
            "description": "Внутренние системы водоснабжения и водоотведения, узлы учёта.",
            "stage": "rd",
            "weight": D("0.147"),
            "min_price": D("80000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "OVIK",
            "name": "Отопление, вентиляция и кондиционирование (ОВиК)",
            "description": "Отопление, приточно-вытяжная вентиляция, кондиционирование и холодоснабжение.",
            "stage": "rd",
            "weight": D("0.284"),
            "min_price": D("120000"),
            "cost_share": D("0.5"),
        },
        {
            "code": "SS",
            "name": "Слаботочные системы (СС)",
            "description": "СКС, ЛВС, СКУД, видеонаблюдение, АПС, СОУЭ, вызов персонала.",
            "stage": "rd",
            "weight": D("0.174"),
            "min_price": D("80000"),
            "cost_share": D("0.5"),
        },
        # Extra sections: weight relative to the standard package
        {
            "code": "TX",
            "name": "Технологические решения (ТХ)",
            "description": "Медицинская технология: расстановка кабинетов и постов, спецификации оборудования.",
            "stage": "rd",
            "weight": D("0.193"),
            "min_price": D("100000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "PB",
            "name": "Мероприятия по обеспечению пожарной безопасности (ПБ)",
            "description": "Пожарные отсеки, СОУЭ, АПС, дымоудаление, противопожарные преграды.",
            "stage": "rd",
            "weight": D("0.183"),
            "min_price": D("80000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "OBS",
            "name": "Обследование конструкций и инженерных систем, обмеры",
            "description": "Визуальное и инструментальное обследование, обмерные работы, фотофиксация дефектов.",
            "stage": "pre",
            "weight": D("0.055"),
            "min_price": D("60000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "TZ",
            "name": "Техническое заключение по результатам обследования",
            "description": "Альбом технического заключения с учётом ГОСТ 31937-2024.",
            "stage": "pre",
            "weight": D("0.037"),
            "min_price": D("50000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "POS",
            "name": "Организация строительства (ПОС/ПОР)",
            "description": "Проект организации работ, стройгенплан, подготовительные работы.",
            "stage": "rd",
            "weight": D("0.046"),
            "min_price": D("50000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "OOS",
            "name": "Охрана окружающей среды (ООС)",
            "description": "Мероприятия по защите от шума и вибрации инженерного оборудования.",
            "stage": "rd",
            "weight": D("0.037"),
            "min_price": D("40000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "ODI",
            "name": "Обеспечение доступа инвалидов (ОДИ)",
            "description": "Решения для маломобильных групп населения.",
            "stage": "rd",
            "weight": D("0.037"),
            "min_price": D("40000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "PP",
            "name": "Проект перепланировки и переустройства",
            "description": "Проект перепланировки, техническое заключение для Росреестра.",
            "stage": "extra",
            "weight": D("0.064"),
            "min_price": D("60000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
        {
            "code": "SM",
            "name": "Сметная документация (СМ)",
            "description": "Локальные и сводные сметные расчёты.",
            "stage": "extra",
            "weight": D("0.180"),
            "min_price": D("80000"),
            "cost_share": D("0.5"),
            "default_selected": False,
        },
    ],
    "object_types": {
        "Медицинский центр / клиника": D("1.0"),
        "Поликлиника": D("1.0"),
        "Стоматология": D("0.95"),
        "Лаборатория": D("1.1"),
        "Диагностический центр": D("1.1"),
        "Больница / стационар": D("1.2"),
    },
    "modifiers": [
        {"code": "reconstruction", "name": "Реконструкция / капремонт", "multiplier": D("1.10")},
        {"code": "clean_rooms", "name": "Чистые помещения / операционные", "multiplier": D("1.25")},
        {"code": "complex_medtech", "name": "Сложная медтехнология (КТ, МРТ, рентген)", "multiplier": D("1.15")},
        {"code": "urgent", "name": "Срочность (сокращённые сроки)", "multiplier": D("1.20")},
    ],
    "regions": {},
}
