"""message links to proposal and organization

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 06:31:16.379794+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("proposal_version_id", sa.Integer(), nullable=True))
    op.add_column("message", sa.Column("organization_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_message_organization_id"), "message", ["organization_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_message_proposal_version_id_proposal_version"),
        "message",
        "proposal_version",
        ["proposal_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_message_organization_id_organization"),
        "message",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("proposal_version", sa.Column("estimate_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_proposal_version_estimate_id_estimate"),
        "proposal_version",
        "estimate",
        ["estimate_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_proposal_version_estimate_id_estimate"), "proposal_version", type_="foreignkey")
    op.drop_column("proposal_version", "estimate_id")
    op.drop_constraint(op.f("fk_message_organization_id_organization"), "message", type_="foreignkey")
    op.drop_constraint(op.f("fk_message_proposal_version_id_proposal_version"), "message", type_="foreignkey")
    op.drop_index(op.f("ix_message_organization_id"), table_name="message")
    op.drop_column("message", "organization_id")
    op.drop_column("message", "proposal_version_id")
    # ### end Alembic commands ###
