"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-03 00:44:25.852618+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_study",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=True),
        sa.Column("area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.String(length=500), nullable=True),
        sa.Column("region", sa.String(length=200), nullable=True),
        sa.Column("stages", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("sections", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("photos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("can_mention_customer", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_study")),
    )
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=True),
        sa.Column("kpp", sa.String(length=9), nullable=True),
        sa.Column("ogrn", sa.String(length=15), nullable=True),
        sa.Column("org_type", sa.String(length=16), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("region", sa.String(length=200), nullable=True),
        sa.Column("is_clinic_chain", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
        sa.UniqueConstraint("inn", name=op.f("uq_organization_inn")),
    )
    op.create_index(op.f("ix_organization_name"), "organization", ["name"], unique=False)
    op.create_table(
        "price_table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_table")),
        sa.UniqueConstraint("name", "version", name=op.f("uq_price_table_name")),
    )
    op.create_table(
        "sequence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sequence")),
        sa.UniqueConstraint("name", name=op.f("uq_sequence_name")),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("connector", sa.String(length=100), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("legal_status", sa.String(length=32), nullable=False),
        sa.Column("schedule_minutes", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("circuit_open_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("name", name=op.f("uq_source_name")),
    )
    op.create_table(
        "stored_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("doc_type", sa.String(length=100), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_document")),
    )
    op.create_index(op.f("ix_stored_document_doc_type"), "stored_document", ["doc_type"], unique=False)
    op.create_index(op.f("ix_stored_document_valid_until"), "stored_document", ["valid_until"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("totp_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_user_telegram_id")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_table(
        "approval",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("double_confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_approval_user_id_user"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.BigInteger(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_audit_log_user_id_user"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_ts"), "audit_log", ["ts"], unique=False)
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=True),
        sa.Column("position", sa.String(length=300), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_note", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_contact_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    op.create_index(op.f("ix_contact_organization_id"), "contact", ["organization_id"], unique=False)
    op.create_table(
        "listing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(length=300), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("region", sa.String(length=200), nullable=True),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("object_type", sa.String(length=100), nullable=True),
        sa.Column("area_m2", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("budget_unknown", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("exclusion_reason", sa.String(length=300), nullable=True),
        sa.Column("lost_reason", sa.String(length=300), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("score_explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedup_hash", sa.String(length=64), nullable=True),
        sa.Column("merged_into_id", sa.Integer(), nullable=True),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("complex_procedure", sa.Boolean(), nullable=False),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["listing.id"],
            name=op.f("fk_listing_merged_into_id_listing"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_listing_organization_id_organization"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_listing_source_id_source"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing")),
        sa.UniqueConstraint("source_id", "external_id", name=op.f("uq_listing_source_id")),
    )
    op.create_index(op.f("ix_listing_deadline_at"), "listing", ["deadline_at"], unique=False)
    op.create_index(op.f("ix_listing_dedup_hash"), "listing", ["dedup_hash"], unique=False)
    op.create_index(op.f("ix_listing_score"), "listing", ["score"], unique=False)
    op.create_index(op.f("ix_listing_source_id"), "listing", ["source_id"], unique=False)
    op.create_index(op.f("ix_listing_status"), "listing", ["status"], unique=False)
    op.create_table(
        "optout",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_optout_organization_id_organization"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optout")),
        sa.UniqueConstraint("value", name=op.f("uq_optout_value")),
    )
    op.create_table(
        "sequence_step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sequence_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("day_offset", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=True),
        sa.Column("prompt_key", sa.String(length=100), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["sequence.id"],
            name=op.f("fk_sequence_step_sequence_id_sequence"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sequence_step")),
    )
    op.create_index(op.f("ix_sequence_step_sequence_id"), "sequence_step", ["sequence_id"], unique=False)
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["user.id"], name=op.f("fk_setting_updated_by_id_user"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_setting")),
    )
    op.create_table(
        "contact_channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("is_public_for_orders", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_channel_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_contact_channel_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_channel")),
        sa.UniqueConstraint("organization_id", "kind", "value", name=op.f("uq_contact_channel_organization_id")),
    )
    op.create_index(op.f("ix_contact_channel_organization_id"), "contact_channel", ["organization_id"], unique=False)
    op.create_table(
        "estimate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("price_table_id", sa.Integer(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("min_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cost_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("scenarios", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listing.id"], name=op.f("fk_estimate_listing_id_listing"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["price_table_id"],
            ["price_table.id"],
            name=op.f("fk_estimate_price_table_id_price_table"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate")),
    )
    op.create_index(op.f("ix_estimate_listing_id"), "estimate", ["listing_id"], unique=False)
    op.create_table(
        "listing_document",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("mime", sa.String(length=200), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("text_extracted", sa.Boolean(), nullable=False),
        sa.Column("parsed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listing.id"],
            name=op.f("fk_listing_document_listing_id_listing"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_document")),
        sa.UniqueConstraint("listing_id", "sha256", name=op.f("uq_listing_document_listing_id")),
    )
    op.create_index(op.f("ix_listing_document_listing_id"), "listing_document", ["listing_id"], unique=False)
    op.create_table(
        "listing_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listing.id"],
            name=op.f("fk_listing_version_listing_id_listing"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_version")),
        sa.UniqueConstraint("listing_id", "version", name=op.f("uq_listing_version_listing_id")),
    )
    op.create_index(op.f("ix_listing_version_listing_id"), "listing_version", ["listing_id"], unique=False)
    op.create_table(
        "participation_package",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_documents", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("instructions_md", sa.Text(), nullable=True),
        sa.Column("checklist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("zip_key", sa.String(length=500), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listing.id"],
            name=op.f("fk_participation_package_listing_id_listing"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participation_package")),
    )
    op.create_index(op.f("ix_participation_package_listing_id"), "participation_package", ["listing_id"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("call_script", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listing.id"], name=op.f("fk_task_listing_id_listing"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_task_organization_id_organization"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
    )
    op.create_index(op.f("ix_task_due_at"), "task", ["due_at"], unique=False)
    op.create_index(op.f("ix_task_listing_id"), "task", ["listing_id"], unique=False)
    op.create_table(
        "thread",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listing.id"], name=op.f("fk_thread_listing_id_listing"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_thread_organization_id_organization"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread")),
    )
    op.create_index(op.f("ix_thread_listing_id"), "thread", ["listing_id"], unique=False)
    op.create_table(
        "calendar_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("stored_document_id", sa.Integer(), nullable=True),
        sa.Column("remind_before_minutes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reminders_sent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listing.id"],
            name=op.f("fk_calendar_event_listing_id_listing"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stored_document_id"],
            ["stored_document.id"],
            name=op.f("fk_calendar_event_stored_document_id_stored_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_calendar_event_task_id_task"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_event")),
    )
    op.create_index(op.f("ix_calendar_event_starts_at"), "calendar_event", ["starts_at"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("from_addr", sa.String(length=500), nullable=True),
        sa.Column("to_addr", sa.String(length=500), nullable=True),
        sa.Column("subject", sa.String(length=1000), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("email_message_id", sa.String(length=500), nullable=True),
        sa.Column("in_reply_to", sa.String(length=500), nullable=True),
        sa.Column("references", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("approval_id", sa.BigInteger(), nullable=True),
        sa.Column("sequence_step_id", sa.Integer(), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=True),
        sa.Column("classification_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("send_attempts", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval.id"],
            name=op.f("fk_message_approval_id_approval"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sequence_step_id"],
            ["sequence_step.id"],
            name=op.f("fk_message_sequence_step_id_sequence_step"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["thread.id"], name=op.f("fk_message_thread_id_thread"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message")),
        sa.UniqueConstraint("email_message_id", name=op.f("uq_message_email_message_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_message_idempotency_key")),
    )
    op.create_index(op.f("ix_message_status"), "message", ["status"], unique=False)
    op.create_index(op.f("ix_message_thread_id"), "message", ["thread_id"], unique=False)
    op.create_table(
        "proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("estimate_id", sa.Integer(), nullable=True),
        sa.Column("template_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["estimate.id"],
            name=op.f("fk_proposal_estimate_id_estimate"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listing.id"], name=op.f("fk_proposal_listing_id_listing"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal")),
    )
    op.create_index(op.f("ix_proposal_listing_id"), "proposal", ["listing_id"], unique=False)
    op.create_table(
        "proposal_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("docx_key", sa.String(length=500), nullable=True),
        sa.Column("pdf_key", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name=op.f("fk_proposal_version_created_by_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.id"],
            name=op.f("fk_proposal_version_proposal_id_proposal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_version")),
        sa.UniqueConstraint("proposal_id", "version", name=op.f("uq_proposal_version_proposal_id")),
    )
    op.create_index(op.f("ix_proposal_version_proposal_id"), "proposal_version", ["proposal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proposal_version_proposal_id"), table_name="proposal_version")
    op.drop_table("proposal_version")
    op.drop_index(op.f("ix_proposal_listing_id"), table_name="proposal")
    op.drop_table("proposal")
    op.drop_index(op.f("ix_message_thread_id"), table_name="message")
    op.drop_index(op.f("ix_message_status"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_calendar_event_starts_at"), table_name="calendar_event")
    op.drop_table("calendar_event")
    op.drop_index(op.f("ix_thread_listing_id"), table_name="thread")
    op.drop_table("thread")
    op.drop_index(op.f("ix_task_listing_id"), table_name="task")
    op.drop_index(op.f("ix_task_due_at"), table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_participation_package_listing_id"), table_name="participation_package")
    op.drop_table("participation_package")
    op.drop_index(op.f("ix_listing_version_listing_id"), table_name="listing_version")
    op.drop_table("listing_version")
    op.drop_index(op.f("ix_listing_document_listing_id"), table_name="listing_document")
    op.drop_table("listing_document")
    op.drop_index(op.f("ix_estimate_listing_id"), table_name="estimate")
    op.drop_table("estimate")
    op.drop_index(op.f("ix_contact_channel_organization_id"), table_name="contact_channel")
    op.drop_table("contact_channel")
    op.drop_table("setting")
    op.drop_index(op.f("ix_sequence_step_sequence_id"), table_name="sequence_step")
    op.drop_table("sequence_step")
    op.drop_table("optout")
    op.drop_index(op.f("ix_listing_status"), table_name="listing")
    op.drop_index(op.f("ix_listing_source_id"), table_name="listing")
    op.drop_index(op.f("ix_listing_score"), table_name="listing")
    op.drop_index(op.f("ix_listing_dedup_hash"), table_name="listing")
    op.drop_index(op.f("ix_listing_deadline_at"), table_name="listing")
    op.drop_table("listing")
    op.drop_index(op.f("ix_contact_organization_id"), table_name="contact")
    op.drop_table("contact")
    op.drop_index(op.f("ix_audit_log_ts"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("approval")
    op.drop_table("user")
    op.drop_index(op.f("ix_stored_document_valid_until"), table_name="stored_document")
    op.drop_index(op.f("ix_stored_document_doc_type"), table_name="stored_document")
    op.drop_table("stored_document")
    op.drop_table("source")
    op.drop_table("sequence")
    op.drop_table("price_table")
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_table("organization")
    op.drop_table("case_study")
    # ### end Alembic commands ###
